### ISSUE TITLE
can you please tell me how to use with vue.js with capacitor.js

### ISSUE THREAD

**Issue by tarangshah19** [MrSpark2591/cordova-app-update-plugin#4]
i am using vue js i want to use this plugin with cpacitor.js can you please give me instruction that how to add this plugin in vue project

**Comment by MrSpark2591** [comment]
It's a Cordova plugin so you can use it with capacitor.js. 

Please follow:
https://capacitorjs.com/docs/v2/cordova/using-cordova-plugins
