### ISSUE TITLE
Install with github and now app hangs

### ISSUE THREAD

**Issue by BenLaKnet** [MrSpark2591/cordova-app-update-plugin#6]
I tried to install plugin with :
cordova plugin add https://github.com/Fasal-Tech/cordova-app-update-plugin

And now app hangs with error : app stops sytematically.

**Comment by 9t96** [comment]
Same happens for me

**Comment by MrSpark2591** [comment]
I have published a new version. Please check here:
https://www.npmjs.com/package/cordova-in-app-update
