### ISSUE TITLE
updatePlugin is an empty object

### ISSUE THREAD

**Issue by sebalr** [MrSpark2591/cordova-app-update-plugin#8]
Im trying to use this plugin with cordova and android@13.
window.plugins has an empty updatePlugin object without update function. I've also check window.cordova.plugins and there is no  updatePlugin there.
Other plugins are working fine in my current setup. I've tried with npm and github installation.
I'm doing something wrong?
Thanks in advance

**Comment by MrSpark2591** [comment]
Hey,
Can you confirm the version?
We are using 2.0.3 in production without facing a similar issue.

**Comment by sebalr** [comment]
Sorry, I'm closing as this was just a log error, the plugin is still not working for us as is not showing update request but maybe is there something wrong with our cordova or google play config
